export interface MenuItem {
  name: string;
  description?: string;
  price: string;
  veg?: boolean;
  spicy?: boolean;
  bestseller?: boolean;
}

export interface MenuCategory {
  id: string;
  name: string;
  items: MenuItem[];
}

export const menuCategories: MenuCategory[] = [
  {
    id: "beverages",
    name: "Beverages",
    items: [
      { name: "Tea", price: "₹25", veg: true },
      { name: "Coffee", price: "₹30", veg: true },
      { name: "Milk", price: "₹30", veg: true },
      { name: "Bournvita", price: "₹30", veg: true },
      { name: "Lassi", price: "₹50", veg: true, bestseller: true },
      { name: "Cold Coffee", price: "₹60", veg: true },
      { name: "Buttermilk", price: "₹30", veg: true },
      { name: "Fresh Lime Soda", price: "₹30", veg: true },
      { name: "Fresh Lime Water", price: "₹20", veg: true },
      { name: "Mineral Water", price: "₹20", veg: true },
    ],
  },
  {
    id: "salads-raita",
    name: "Salads & Raita",
    items: [
      { name: "Green Salad", price: "₹80", veg: true },
      { name: "Kachumber Salad", price: "₹60", veg: true },
      { name: "Tandoori Salad", price: "₹90", veg: true },
      { name: "Boondi Raita", price: "₹90", veg: true },
      { name: "Veg Raita", price: "₹80", veg: true },
      { name: "Pineapple Raita", price: "₹150", veg: true },
      { name: "Plain Curd", price: "₹60", veg: true },
    ],
  },
  {
    id: "papad",
    name: "Papad",
    items: [
      { name: "Udad Roast", price: "₹15", veg: true },
      { name: "Udad Fry", price: "₹20", veg: true },
      { name: "Udad Masala", price: "₹30", veg: true },
      { name: "Udad Cheese", price: "₹60", veg: true },
      { name: "Nagli Roast", price: "₹20", veg: true },
      { name: "Nagli Fry", price: "₹30", veg: true },
      { name: "Nagli Masala", price: "₹35", veg: true },
      { name: "Jaipuri Papad", price: "₹50", veg: true },
      { name: "Papad Bhurji", price: "₹80", veg: true },
    ],
  },
  {
    id: "veg-chinese",
    name: "Veg Chinese Starters & Snacks",
    items: [
      { name: "Veg Manchurian", price: "₹130", veg: true },
      { name: "Gobi Manchurian", price: "₹120", veg: true },
      { name: "Veg Crispy", price: "₹200", veg: true },
      { name: "Veg Spring Roll", price: "₹200", veg: true },
      { name: "Veg Hot Pan", price: "₹220", veg: true },
      { name: "Soyabean Chilli", price: "₹100", veg: true, spicy: true },
      { name: "Mushroom Chilli", price: "₹200", veg: true, spicy: true },
      { name: "Paneer Chilli", price: "₹200", veg: true, spicy: true, bestseller: true },
      { name: "Paneer Hot Pan", price: "₹230", veg: true },
      { name: "Paneer Sathe", price: "₹250", veg: true },
      { name: "Paneer in Schezwan", price: "₹230", veg: true, spicy: true },
      { name: "Paneer 65", price: "₹230", veg: true },
      { name: "Paneer Manchurian", price: "₹190", veg: true },
      { name: "Paneer Dragon Roll", price: "₹230", veg: true },
      { name: "Paneer Saski Roll", price: "₹240", veg: true },
      { name: "Paneer Cheese Balls", price: "₹250", veg: true },
      { name: "Paneer Hong Kong Style", price: "₹230", veg: true },
      { name: "Paneer Red Sauce", price: "₹250", veg: true },
      { name: "Paneer Basket", price: "₹220", veg: true },
      { name: "Paneer Garlic", price: "₹180", veg: true },
      { name: "Paneer Salt & Pepper", price: "₹200", veg: true },
      { name: "Paneer China Town", price: "₹300", veg: true },
      { name: "Paneer Tarunes", price: "₹300", veg: true },
      { name: "Veg Lollipop", price: "₹200", veg: true },
      { name: "Veg Sizzler", price: "₹330", veg: true },
      { name: "Veg Bullet", price: "₹200", veg: true },
      { name: "Veg Crunchy", price: "₹210", veg: true },
      { name: "Veg Tarunes", price: "₹260", veg: true },
      { name: "Boiled Veg", price: "₹130", veg: true },
      { name: "Honey Potato Chilli", price: "₹200", veg: true },
      { name: "Crispy Corn Chilli", price: "₹200", veg: true, spicy: true },
      { name: "Baby Corn Chilli", price: "₹190", veg: true, spicy: true },
    ],
  },
  {
    id: "non-veg-chinese",
    name: "Non-Veg Chinese Starters & Snacks",
    items: [
      { name: "Chicken Chilli (Boneless)", price: "₹200", veg: false, spicy: true, bestseller: true },
      { name: "Chicken Chilli (Bone)", price: "₹280", veg: false, spicy: true },
      { name: "Chicken Red Sauce", price: "₹260", veg: false },
      { name: "Chicken Hong Kong", price: "₹280", veg: false },
      { name: "Chicken Satay", price: "₹250", veg: false },
      { name: "Chicken Garlic Sauce", price: "₹220", veg: false },
      { name: "Chicken Salt & Pepper", price: "₹200", veg: false },
      { name: "Chicken Basket", price: "₹250", veg: false },
      { name: "Chicken Crispy", price: "₹230", veg: false },
      { name: "Chicken Manchurian", price: "₹220", veg: false },
      { name: "Chicken 65", price: "₹230", veg: false, spicy: true },
      { name: "Chicken Lollipop (6 pcs)", price: "₹240", veg: false },
      { name: "Chicken Kentucky", price: "₹260", veg: false },
      { name: "Chicken Hot & Garlic", price: "₹220", veg: false, spicy: true },
      { name: "Chicken Roast", price: "₹190", veg: false },
      { name: "Mutton Chilli", price: "₹350", veg: false, spicy: true },
      { name: "Mutton Roast", price: "₹300", veg: false },
      { name: "Egg Chilli", price: "₹180", veg: false, spicy: true },
      { name: "Fish Chilli", price: "₹180", veg: false, spicy: true },
      { name: "Fish Roast Laplari", price: "₹200", veg: false },
      { name: "Fish Sathe", price: "₹220", veg: false },
      { name: "Boiled Egg (2 pcs)", price: "₹30", veg: false },
      { name: "Egg Boiled Fry", price: "₹60", veg: false },
    ],
  },
  {
    id: "veg-tandoor",
    name: "Veg Tandoor Starters",
    items: [
      { name: "Paneer Tikka", price: "₹220", veg: true, bestseller: true },
      { name: "Paneer Achari Tikka", price: "₹220", veg: true },
      { name: "Paneer Pahadi Kabab", price: "₹250", veg: true },
      { name: "Paneer Reshmi Kabab", price: "₹300", veg: true },
      { name: "Paneer Angara Kabab", price: "₹260", veg: true, spicy: true },
      { name: "Paneer Guldasta Kabab", price: "₹280", veg: true },
      { name: "Paneer Tiranga Kabab", price: "₹300", veg: true },
      { name: "Stuffed Paneer Tikka", price: "₹280", veg: true },
    ],
  },
  {
    id: "veg-main",
    name: "Veg Main Course",
    items: [
      { name: "Veg Kadai", price: "₹200", veg: true },
      { name: "Veg Begam Bahar", price: "₹250", veg: true },
      { name: "Veg Banjara", price: "₹230", veg: true },
      { name: "Veg Kolhapuri", price: "₹210", veg: true, spicy: true },
      { name: "Veg Patiyala", price: "₹260", veg: true },
      { name: "Veg Kofta", price: "₹200", veg: true },
      { name: "Veg Maratha", price: "₹200", veg: true },
      { name: "Aloo Mutter", price: "₹200", veg: true },
      { name: "Kaju Masala", price: "₹260", veg: true },
      { name: "Kaju Curry", price: "₹260", veg: true },
      { name: "Kaju Paneer Masala", price: "₹280", veg: true },
      { name: "Special Sev Bhaji", price: "₹150", veg: true },
      { name: "Sev Tadka", price: "₹150", veg: true },
      { name: "Sev Bhaji", price: "₹120", veg: true },
      { name: "Chana Masala", price: "₹150", veg: true },
      { name: "Malai Kofta", price: "₹230", veg: true },
      { name: "Dum Aloo Punjabi", price: "₹200", veg: true },
      { name: "Mushroom Masala", price: "₹210", veg: true },
      { name: "Veg Takatak", price: "₹200", veg: true },
    ],
  },
  {
    id: "veg-special",
    name: "Veg Special Dishes",
    items: [
      { name: "Paneer Garden", price: "₹470", veg: true },
      { name: "Veg Garden", price: "₹460", veg: true },
      { name: "Veg Rajwadi", price: "₹390", veg: true },
      { name: "Paneer Rajwadi", price: "₹400", veg: true },
      { name: "Paneer Chingari", price: "₹350", veg: true, spicy: true },
      { name: "Kaju Sindoori Masala", price: "₹360", veg: true },
      { name: "Kaju Paneer Tukda", price: "₹400", veg: true },
      { name: "Special White House Paneer", price: "₹360", veg: true, bestseller: true },
      { name: "Kaju Paneer Kundan", price: "₹450", veg: true },
      { name: "Paneer Lababdar", price: "₹350", veg: true },
      { name: "Paneer Lacchedar", price: "₹385", veg: true },
      { name: "Paneer Agbari Masala", price: "₹390", veg: true },
      { name: "Veg Agbari", price: "₹320", veg: true },
      { name: "Veg All Mix", price: "₹300", veg: true },
      { name: "Veg Tiranga", price: "₹350", veg: true },
      { name: "Veg Darbaar", price: "₹380", veg: true },
      { name: "Paneer Kasata", price: "₹400", veg: true },
      { name: "Paneer Mushroom Bhatinda", price: "₹410", veg: true },
      { name: "Kaju Paneer Bhatinda", price: "₹410", veg: true },
      { name: "Paneer Rubabdar", price: "₹360", veg: true },
      { name: "Paneer Changeji", price: "₹400", veg: true },
      { name: "Paneer Kingdom", price: "₹430", veg: true, bestseller: true },
      { name: "Paneer Kundan", price: "₹400", veg: true },
      { name: "Paneer Ruzali Masala", price: "₹410", veg: true },
      { name: "Veg Rubabdar", price: "₹300", veg: true },
      { name: "Veg Dil Bahar", price: "₹350", veg: true },
      { name: "Veg Chilli Milli", price: "₹360", veg: true },
    ],
  },
];
