export interface MenuItem {
  name: string;
  description?: string;
  price: string;
  veg?: boolean;
  spicy?: boolean;
  bestseller?: boolean;
}

export interface MenuCategory {
  id: string;
  name: string;
  items: MenuItem[];
}

export const menuCategories: MenuCategory[] = [
  {
    id: "beverages",
    name: "Veg Good Morning (Beverages)",
    items: [
      { name: "Tea", price: "₹25", veg: true },
      { name: "Coffee", price: "₹30", veg: true },
      { name: "Milk", price: "₹30", veg: true },
      { name: "Bournvita", price: "₹30", veg: true },
      { name: "Lassi", price: "₹50", veg: true, bestseller: true },
      { name: "Cold Coffee", price: "₹60", veg: true },
      { name: "Butter Milk", price: "₹30", veg: true },
      { name: "Fresh Lime Soda", price: "₹30", veg: true },
      { name: "Fresh Lime Water", price: "₹20", veg: true },
      { name: "Mineral Water", price: "₹20", veg: true },
    ],
  },
  {
    id: "salads-raita",
    name: "Salad & Raita",
    items: [
      { name: "Green Salad", price: "₹80", veg: true },
      { name: "Kachumber Salad", price: "₹60", veg: true },
      { name: "Tandoori Salad", price: "₹90", veg: true },
      { name: "Boondi Raita", price: "₹90", veg: true },
      { name: "Veg Raita", price: "₹80", veg: true },
      { name: "Pineapple Raita", price: "₹150", veg: true },
      { name: "Plain Curd", price: "₹60", veg: true },
    ],
  },
  {
    id: "papad",
    name: "Papad",
    items: [
      { name: "Udid Roast / Fry", price: "₹15/20", veg: true },
      { name: "Udid Masala / Cheese", price: "₹30/60", veg: true },
      { name: "Nagli Roast / Fry", price: "₹20/30", veg: true },
      { name: "Nagli Masala", price: "₹35", veg: true },
      { name: "Jaipuri Papad", price: "₹50", veg: true },
      { name: "Papad Bhurji", price: "₹80", veg: true },
    ],
  },
  {
    id: "veg-chinese",
    name: "Veg Chinese / Snacks",
    items: [
      { name: "Veg Manchurian", price: "₹130", veg: true },
      { name: "Gobi Manchurian", price: "₹120", veg: true },
      { name: "Veg Crispy", price: "₹200", veg: true },
      { name: "Veg Spring Roll", price: "₹200", veg: true },
      { name: "Veg Hot Pan", price: "₹220", veg: true },
      { name: "Soyabean Chilli", price: "₹100", veg: true, spicy: true },
      { name: "Mushroom Chilli", price: "₹200", veg: true, spicy: true },
      { name: "Paneer Chilli", price: "₹200", veg: true, spicy: true, bestseller: true },
      { name: "Paneer Hot Pan", price: "₹230", veg: true },
      { name: "Paneer Sathe", price: "₹250", veg: true },
      { name: "Paneer in Schezwan", price: "₹230", veg: true, spicy: true },
      { name: "Paneer 65", price: "₹230", veg: true },
      { name: "Paneer Manchurian", price: "₹190", veg: true },
      { name: "Paneer Dragon Roll", price: "₹230", veg: true },
      { name: "Paneer Saski Roll", price: "₹240", veg: true },
      { name: "Paneer Cheese Balls", price: "₹250", veg: true },
      { name: "Paneer Hong Kong Style", price: "₹230", veg: true },
      { name: "Paneer Red Sauce", price: "₹250", veg: true },
      { name: "Paneer Basket", price: "₹220", veg: true },
      { name: "Paneer Garlic", price: "₹180", veg: true },
      { name: "Paneer Salt & Pepper", price: "₹200", veg: true },
      { name: "Paneer China Town", price: "₹300", veg: true },
      { name: "Paneer Tarunes", price: "₹300", veg: true },
      { name: "Veg Lollipop", price: "₹200", veg: true },
      { name: "Veg Sizzler", price: "₹330", veg: true },
      { name: "Veg Bullet", price: "₹200", veg: true },
      { name: "Veg Crunchy", price: "₹210", veg: true },
      { name: "Veg Tarunes", price: "₹260", veg: true },
      { name: "Boiled Veg", price: "₹130", veg: true },
      { name: "Honey Potato Chilli", price: "₹200", veg: true },
      { name: "Crispy Corn Chilli", price: "₹200", veg: true, spicy: true },
      { name: "Baby Corn Chilli", price: "₹190", veg: true, spicy: true },
    ],
  },
  {
    id: "non-veg-snacks",
    name: "Non-Veg Snacks",
    items: [
      { name: "Chicken Chilli (Boneless)", price: "₹200", veg: false, spicy: true, bestseller: true },
      { name: "Chicken Chilli (Bone)", price: "₹280", veg: false, spicy: true },
      { name: "Chicken Red Sauce", price: "₹260", veg: false },
      { name: "Chicken Hong Kong", price: "₹280", veg: false },
      { name: "Chicken Satay", price: "₹250", veg: false },
      { name: "Chicken Garlic Sauce", price: "₹220", veg: false },
      { name: "Chicken Salt & Pepper", price: "₹200", veg: false },
      { name: "Chicken Basket", price: "₹250", veg: false },
      { name: "Chicken Crispy", price: "₹230", veg: false },
      { name: "Chicken Manchurian", price: "₹220", veg: false },
      { name: "Chicken 65", price: "₹230", veg: false, spicy: true },
      { name: "Chicken Lollipop (6 pcs)", price: "₹240", veg: false },
      { name: "Chicken Kentucky", price: "₹260", veg: false },
      { name: "Chicken Hot & Garlic", price: "₹220", veg: false, spicy: true },
      { name: "Chicken Roast", price: "₹190", veg: false },
      { name: "Mutton Chilli", price: "₹350", veg: false, spicy: true },
      { name: "Mutton Roast", price: "₹300", veg: false },
      { name: "Egg Chilli", price: "₹180", veg: false, spicy: true },
      { name: "Fish Chilli", price: "₹180", veg: false, spicy: true },
      { name: "Fish Roast Laplari", price: "₹200", veg: false },
      { name: "Fish Sathe", price: "₹220", veg: false },
      { name: "Boiled Egg (2 pcs)", price: "₹30", veg: false },
      { name: "Egg Boiled Fry (2 pcs)", price: "₹60", veg: false },
    ],
  },
  {
    id: "veg-tandoor",
    name: "Veg Tandoor Starters",
    items: [
      { name: "Paneer Tikka", price: "₹220", veg: true, bestseller: true },
      { name: "Paneer Achari Tikka", price: "₹220", veg: true },
      { name: "Paneer Pahadi Kabab", price: "₹250", veg: true },
      { name: "Paneer Reshmi Kabab", price: "₹300", veg: true },
      { name: "Paneer Angara Kabab", price: "₹260", veg: true, spicy: true },
      { name: "Paneer Guldasta Kabab", price: "₹280", veg: true },
      { name: "Paneer Tiranga Kabab", price: "₹300", veg: true },
      { name: "Stuffed Paneer Tikka", price: "₹280", veg: true },
      { name: "Veg Harabhara Kabab Masala", price: "₹350", veg: true },
      { name: "Kaju Paneer Angara", price: "₹300", veg: true },
      { name: "Stuff Paneer Pasana", price: "₹410", veg: true },
      { name: "White House Spe. Paneer Stuff", price: "₹400", veg: true, bestseller: true },
    ],
  },
  {
    id: "non-veg-tandoor",
    name: "Non-Veg Tandoor Starters",
    items: [
      { name: "Chicken Ran", price: "₹599", veg: false, bestseller: true },
      { name: "Tandoor Combo", price: "₹330", veg: false },
      { name: "Chicken Multani Tikka", price: "₹350", veg: false },
      { name: "Chicken Angari Ke Kabab", price: "₹320", veg: false },
      { name: "Chicken Chandani Kabab", price: "₹300", veg: false },
      { name: "White House Seek Spe. Kabab", price: "₹350", veg: false, bestseller: true },
      { name: "Chicken Fidroshi Kabab", price: "₹350", veg: false },
    ],
  },
  {
    id: "veg-main",
    name: "Veg Main Course",
    items: [
      { name: "Veg Kadai", price: "₹200", veg: true },
      { name: "Veg Begam Bahar", price: "₹250", veg: true },
      { name: "Veg Banjara", price: "₹230", veg: true },
      { name: "Veg Kolhapuri", price: "₹210", veg: true, spicy: true },
      { name: "Veg Patiyala", price: "₹260", veg: true },
      { name: "Veg Kofta", price: "₹200", veg: true },
      { name: "Veg Maratha", price: "₹200", veg: true },
      { name: "Aloo Mutter", price: "₹200", veg: true },
      { name: "Kaju Masala", price: "₹260", veg: true },
      { name: "Kaju Curry", price: "₹260", veg: true },
      { name: "Kaju Paneer Masala", price: "₹280", veg: true },
      { name: "Spe. Sev Bhaji", price: "₹150", veg: true },
      { name: "Sev Tadka", price: "₹150", veg: true },
      { name: "Sev Bhaji", price: "₹120", veg: true },
      { name: "Chana Masala", price: "₹150", veg: true },
      { name: "Malai Kofta", price: "₹230", veg: true },
      { name: "Dum Aloo Punjabi", price: "₹200", veg: true },
      { name: "Mushroom Masala", price: "₹210", veg: true },
      { name: "Veg Takatak", price: "₹200", veg: true },
    ],
  },
  {
    id: "veg-special",
    name: "Veg Special Dishes",
    items: [
      { name: "Paneer Garden", price: "₹470", veg: true },
      { name: "Veg Garden", price: "₹460", veg: true },
      { name: "Veg Rajwadi", price: "₹390", veg: true },
      { name: "Paneer Rajwadi", price: "₹400", veg: true },
      { name: "Paneer Chingari", price: "₹350", veg: true, spicy: true },
      { name: "Kaju Sindoori Masala", price: "₹360", veg: true },
      { name: "Kaju Paneer Tukda", price: "₹400", veg: true },
      { name: "Special White House Paneer", price: "₹360", veg: true, bestseller: true },
      { name: "Kaju Paneer Kundan", price: "₹450", veg: true },
      { name: "Paneer Lababdar", price: "₹350", veg: true },
      { name: "Paneer Lacchedar", price: "₹385", veg: true },
      { name: "Paneer Agbari Masala", price: "₹390", veg: true },
      { name: "Veg Agbari", price: "₹320", veg: true },
      { name: "Veg All Mix", price: "₹300", veg: true },
      { name: "Veg Tiranga", price: "₹350", veg: true },
      { name: "Veg Darbaar", price: "₹380", veg: true },
      { name: "Paneer Kasata", price: "₹400", veg: true },
      { name: "Paneer Mushroom Bhatinda", price: "₹410", veg: true },
      { name: "Kaju Paneer Bhatinda", price: "₹410", veg: true },
      { name: "Paneer Rubabdar", price: "₹360", veg: true },
      { name: "Paneer Changeji", price: "₹400", veg: true },
      { name: "Paneer Kingdom", price: "₹430", veg: true, bestseller: true },
      { name: "Paneer Kundan", price: "₹400", veg: true },
      { name: "Paneer Ruzali Masala", price: "₹410", veg: true },
      { name: "Veg Rubabdar", price: "₹300", veg: true },
      { name: "Veg Dil Bahar", price: "₹350", veg: true },
      { name: "Veg Chilli Milli", price: "₹360", veg: true },
    ],
  },
  {
    id: "chinese-special",
    name: "Chinese Special Dish",
    items: [
      { name: "KFC Leg (4 pieces)", price: "₹350", veg: false },
      { name: "KFC Leg (Half, 2 pieces)", price: "₹200", veg: false },
      { name: "KFC Chicken Kurkure", price: "₹250", veg: false },
      { name: "KFC Paneer Kurkure", price: "₹250", veg: true },
      { name: "Paneer Cheese Roll", price: "₹250", veg: true },
      { name: "Kaju Paneer Kalimiri", price: "₹360", veg: true },
      { name: "Special Chinese", price: "₹300", veg: true },
      { name: "Paneer Multani", price: "₹280", veg: true },
      { name: "Paneer Chinese Combo", price: "₹280", veg: true },
      { name: "Spe. Paneer Kurkure Chinese", price: "₹350", veg: true },
      { name: "Paneer Mangolian", price: "₹280", veg: true },
    ],
  },
  {
    id: "non-veg-main",
    name: "Non-Veg Main Course",
    items: [
      { name: "Butter Chicken Handi (Full/Half)", price: "₹900/500", veg: false, bestseller: true },
      { name: "Murgh Musallam", price: "₹1100/600", veg: false },
      { name: "Gavrani Chicken Handi (Full)", price: "₹1200", veg: false },
      { name: "Gavrani Chicken Handi (Half)", price: "₹700", veg: false },
      { name: "Gavrani Chicken (Plate)", price: "₹300", veg: false },
      { name: "Special White House", price: "₹400", veg: false },
      { name: "Boiler Chicken Handi (Full)", price: "₹750", veg: false },
      { name: "Boiler Chicken Handi (Half)", price: "₹400", veg: false },
      { name: "Boiler Chicken Curry (Plate)", price: "₹200", veg: false },
      { name: "Chicken Latpat", price: "₹220", veg: false },
      { name: "Chicken Saagwala", price: "₹220", veg: false },
      { name: "Chicken Tikka Masala", price: "₹250", veg: false, bestseller: true },
      { name: "Chicken Kadai", price: "₹230", veg: false },
      { name: "Chicken Bhuna", price: "₹250", veg: false },
      { name: "Chicken Zafrani", price: "₹250", veg: false },
      { name: "Chicken Lahori", price: "₹230", veg: false },
      { name: "Chicken Dahiwala", price: "₹220", veg: false },
      { name: "Chicken Do Pyaza", price: "₹200", veg: false },
      { name: "Chicken Rada Masala", price: "₹250", veg: false },
      { name: "Chicken Shahi Korma", price: "₹250", veg: false },
      { name: "Mutton Patiala", price: "₹450", veg: false },
      { name: "Chicken Gadar Masala (F/H)", price: "₹800/450", veg: false },
      { name: "Chicken Bhuna Masala (F/H)", price: "₹800/450", veg: false },
      { name: "Chicken Bhuna Masala", price: "₹270", veg: false },
      { name: "Mutton Handi (Full/Half)", price: "₹1200/650", veg: false },
      { name: "Mutton Curry (Plate)", price: "₹330", veg: false },
      { name: "Mutton Bhuna", price: "₹350", veg: false },
      { name: "Mutton Saagwala", price: "₹330", veg: false },
      { name: "Mutton Kadhai", price: "₹360", veg: false },
      { name: "Mutton Masala", price: "₹350", veg: false },
      { name: "Mutton Latpat", price: "₹330", veg: false },
      { name: "Mutton Tawa", price: "₹350", veg: false },
      { name: "Mutton Rogan Josh", price: "₹400", veg: false },
      { name: "Mutton Keema", price: "₹500", veg: false },
      { name: "Fish Curry (Plate)", price: "₹200", veg: false },
      { name: "Fish Masala", price: "₹220", veg: false },
      { name: "Egg Curry", price: "₹170", veg: false },
      { name: "Egg Masala", price: "₹210", veg: false },
      { name: "Fish Handi (F/H)", price: "₹400/700", veg: false },
      { name: "Prawns Curry", price: "As per availability", veg: false },
      { name: "Surmai Curry", price: "As per availability", veg: false },
      { name: "Pomfret Curry", price: "As per availability", veg: false },
      { name: "Chicken Rubabdar", price: "₹400", veg: false },
      { name: "Chicken Malvani Full Handi", price: "₹1000", veg: false },
      { name: "Chicken Malvani Half Handi", price: "₹550", veg: false },
      { name: "Chicken Moglai Full Handi", price: "₹1100", veg: false },
      { name: "Chicken Moglai Half Handi", price: "₹600", veg: false },
      { name: "Murga Afghani Handi (F/H)", price: "₹1200/600", veg: false },
      { name: "Chicken Shahoji (F/H)", price: "₹550/1000", veg: false },
      { name: "Mutton Shahoji (F/H)", price: "₹700/1300", veg: false },
      { name: "Spe. Murg Leg (F/H)", price: "₹1100/600", veg: false },
    ],
  },
  {
    id: "indian-pulses",
    name: "Indian Pulses (Dal)",
    items: [
      { name: "Dal Fry", price: "₹110", veg: true },
      { name: "Dal Tadka", price: "₹130", veg: true },
      { name: "Dal Makhani", price: "₹160", veg: true, bestseller: true },
      { name: "Dal Palak", price: "₹150", veg: true },
      { name: "Dal Jeera", price: "₹100", veg: true },
    ],
  },
  {
    id: "tandoori-breads",
    name: "Tandoori (Breads)",
    items: [
      { name: "Tandoori Roti", price: "₹15", veg: true },
      { name: "Butter Roti", price: "₹20", veg: true },
      { name: "Missi Roti", price: "₹30", veg: true },
      { name: "Naan", price: "₹40", veg: true },
      { name: "Butter Naan", price: "₹45", veg: true, bestseller: true },
      { name: "Cheese Naan / Butter", price: "₹80", veg: true },
      { name: "Laccha Paratha / Butter", price: "₹50", veg: true },
      { name: "Stuffed Kulcha", price: "₹120", veg: true },
      { name: "Aloo Paratha", price: "₹110", veg: true },
      { name: "Paneer Paratha", price: "₹120", veg: true },
      { name: "Methi Paratha", price: "₹80", veg: true },
      { name: "Butter Kulcha", price: "₹50", veg: true },
      { name: "Garlic Naan", price: "₹60", veg: true },
      { name: "Kashmiri Naan", price: "₹100", veg: true },
      { name: "Roti Basket", price: "₹300", veg: true },
      { name: "Chapati", price: "₹15", veg: true },
      { name: "Butter Chapati", price: "₹20", veg: true },
      { name: "Bhakar / Butter", price: "₹20/25", veg: true },
      { name: "Fulka", price: "₹20/25", veg: true },
      { name: "Butter Fulka", price: "₹25", veg: true },
    ],
  },
  {
    id: "veg-rice-biryani",
    name: "Veg Rice & Biryani",
    items: [
      { name: "Steam Rice", price: "₹70/110", veg: true },
      { name: "Jeera Rice", price: "₹80/120", veg: true },
      { name: "Veg Pulav", price: "₹200", veg: true },
      { name: "Peas Pulav", price: "₹180", veg: true },
      { name: "Veg Biryani", price: "₹220", veg: true },
      { name: "Veg Hyderabadi Biryani", price: "₹230", veg: true, bestseller: true },
      { name: "Kashmiri Pulav", price: "₹220", veg: true },
      { name: "Curd Rice", price: "₹180", veg: true },
      { name: "Masala Rice", price: "₹160", veg: true },
      { name: "Dal Khichdi", price: "₹130", veg: true },
      { name: "Butter Khichdi", price: "₹150", veg: true },
      { name: "Palak Khichdi", price: "₹130", veg: true },
      { name: "Paneer Tikka Biryani", price: "₹270", veg: true },
    ],
  },
  {
    id: "non-veg-rice-biryani",
    name: "Non-Veg Rice & Biryani",
    items: [
      { name: "Egg Biryani", price: "₹200", veg: false },
      { name: "Mutton Biryani", price: "₹360", veg: false },
      { name: "Mutton Hyderabadi Biryani", price: "₹400", veg: false, bestseller: true },
      { name: "Chicken Hyderabadi Biryani", price: "₹250", veg: false, bestseller: true },
      { name: "Chicken Biryani", price: "₹230", veg: false },
      { name: "Fish Biryani", price: "₹200", veg: false },
      { name: "Chicken Hyderabadi Dum Biryani", price: "₹300", veg: false },
      { name: "Mutton Hyderabadi Dum Biryani", price: "₹420", veg: false },
    ],
  },
  {
    id: "as-per-availability",
    name: "As Per Availability (Seafood)",
    items: [
      { name: "Surmai / Dokin", price: "As per availability", veg: false },
      { name: "Pomfret / Lalpari", price: "As per availability", veg: false },
      { name: "Prawns / Rahu", price: "As per availability", veg: false },
    ],
  },
  {
    id: "chinese-veg-rice-noodles",
    name: "Chinese Veg Rice & Noodles",
    items: [
      { name: "Veg Fried Rice", price: "₹180", veg: true },
      { name: "Mushroom Fried Rice", price: "₹200", veg: true },
      { name: "Veg Chowmein", price: "₹160", veg: true },
      { name: "Veg Hakka Noodles", price: "₹150", veg: true },
      { name: "Veg Schezwan Noodles", price: "₹180", veg: true, spicy: true },
      { name: "Hong Kong Rice & Noodles", price: "₹220", veg: true },
      { name: "Veg Schezwan Rice", price: "₹180", veg: true, spicy: true },
      { name: "Veg Tripple Schezwan", price: "₹280", veg: true, spicy: true },
      { name: "Veg Manchurian Rice", price: "₹200", veg: true },
    ],
  },
  {
    id: "chinese-non-veg-rice-noodles",
    name: "Chinese Non-Veg Rice & Noodles",
    items: [
      { name: "Chicken Fried Rice", price: "₹200", veg: false },
      { name: "Chicken Chowmein", price: "₹180", veg: false },
      { name: "Chicken Hakka Noodles", price: "₹180", veg: false },
      { name: "Chicken Hongkong Rice & Noodles", price: "₹250", veg: false },
      { name: "Chicken Tripple Schezwan Rice", price: "₹300", veg: false, spicy: true },
      { name: "Chicken Schezwan Rice & Noodles", price: "₹320", veg: false, spicy: true },
      { name: "Egg Fried Rice", price: "₹180", veg: false },
    ],
  },
  {
    id: "white-house-special",
    name: "White House Special",
    items: [
      { name: "White House Sp. Biryani (H/F)", price: "₹120/200", veg: true, bestseller: true },
      { name: "Chicken Biryani (H/F)", price: "₹70/120", veg: false },
      { name: "Mutton Biryani (H/F)", price: "₹150/220", veg: false },
      { name: "Egg Biryani (H/F)", price: "₹60/110", veg: false },
      { name: "Veg Biryani (H/F)", price: "₹70/120", veg: true },
    ],
  },
];
